"""Add assigned_university_id column

Revision ID: 45486b284234
Revises: cc90bf314e3b
Create Date: 2023-10-16 13:44:45.755256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45486b284234'
down_revision = 'cc90bf314e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_university_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'university', ['assigned_university_id'], ['id'])
        batch_op.drop_column('assigned_university')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_university', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_university_id')

    # ### end Alembic commands ###
