"""empty message

Revision ID: 5717ed1784ad
Revises: 
Create Date: 2023-10-11 10:28:57.394656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5717ed1784ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('university_study_area')
    op.drop_table('student_university')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_university',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('university_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'university_id')
    )
    op.create_table('university_study_area',
    sa.Column('university_id', sa.INTEGER(), nullable=False),
    sa.Column('study_area_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_area.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('university_id', 'study_area_id')
    )
    # ### end Alembic commands ###
