"""empty message

Revision ID: c55ebf53c725
Revises: 5717ed1784ad
Create Date: 2023-10-14 09:13:11.045737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55ebf53c725'
down_revision = '5717ed1784ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('major')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
